### ISSUE TITLE
LED Colors

### ISSUE THREAD

**Issue by MrTinker64** [SFUnity/Quake#25]

**Comment by Marshalllllllllll** [comment]
Red: no note in intake or shooter
Green or Blue (based on which one is easier to see on practice field): note in intake or shooter (light on when distance sensor in indexer or shooter sees a note. This will allow me to pull up the intake as soon as note is far enough through. This may help Ryan too, but I think we can generally tell when we have a note in the intake)

**Comment by Marshalllllllllll** [comment]
I think it may be beneficial to have the same lights in auto, so drive team knows when to hit a-stop, but, if we decide it isn’t helpful, we should make the lights in auto cycle between red orange and yellow.

**Comment by RYon187** [comment]
Here's what I think they should be:
Red -> no note in intake + no speaker or source April tag detected
Blue -> note in intake / ready to shoot + no speaker or source april tag detected
Purple? -> note in intake / ready to shoot + speaker or source april tag detected but not lined up 
Green -> ready to shoot + aligned with April tag

This system would ensure that the lights are always Red if we don't have a note even if we are aligned with a tag. But if we do have a note, it progresses in steps (Blue for note, purple for sees April tag, and green for everything lined up) and should hopefully be easy to comprehend, although it is a lot of colors. Let me know what you guys think though, I could be overcomplicating things

**Comment by MrTinker64** [comment]
I don't think you're over complicating. It's important for it rob lined up and then you hit the X button. It may be a dead give away to other teams though. We'll also need to figure out what tolerance to use, we could scale it with distance. Would you want it to need both drivebase and shooter ready?

**Comment by MrTinker64** [comment]
@MrTinker64 finalize with m and r
